<a href="https://colab.research.google.com/github/ryantang444/Chemstuff/blob/main/scheduling_tool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import itertools

In [5]:
df = pd.read_csv("/content/Fall Enrollment Data - Sheet1 (1).csv")
df

    Unnamed: 0 Combination: Unnamed: 2  Fall 2022  Fall 2021  Fall 2019
0            0      BIO 105   PHYS 110          1          0          0
1            1      BIO 105   MATH 120          2          2          0
2            2      BIO 105   MATH 110          1          2          2
3            3      BIO 105   CHEM 120          2          2          2
4            4      BIO 105   CHEM 130          0          1          0
5            5      BIO 105    BIO 130          1          1          1
6            6      BIO 105   MATH 114          0          0          1
7            7      BIO 115   CHEM 120          3          5         13
8            8      BIO 115   CHEM 130          0          0          2
9            9      BIO 115   MATH 110          1          1          1
10          10      BIO 115   MATH 114          2          0          2
11          11      BIO 115   MATH 120          0          0          2
12          12      BIO 115   MATH 128          0          0          2
13          13      BIO 115   PHYS 110          0          0          1
14          14      BIO 115   PHYS 230          0          0          1
15          15      BIO 130   CHEM 120          3          2          4
16          16      BIO 130   CHEM 130          1          0          0
17          17      BIO 130   MATH 110          0          0          4
18          18      BIO 130   MATH 120          4          1          1
19          19      BIO 130   MATH 128          0          0          1
20          20     CHEM 120   MATH 110          8         15         11
21          21     CHEM 120   MATH 120          4          2          6
22          22     CHEM 120   MATH 114          4          0         11
23          23     CHEM 120   MATH 128          0          0          3
24          24     CHEM 120   PHYS 110          2          0          1
25          25     CHEM 130   MATH 110          2          1          2
26          26     CHEM 130   MATH 114          1          0          0
27          27     CHEM 130   MATH 120          0          1          2
28          28     CHEM 130   MATH 128          0          0          3
29          29     CHEM 130   PHYS 110          1          0          1
30          30     CHEM 130   PHYS 230          0          0          3
31          31     MATH 110   PHYS 110          6          4          7
32          32     MATH 120   PHYS 110          3          2          3
33          33     MATH 120   PHYS 115          1          1          1
34          34     MATH 114   PHYS 110          5          3          3
35          35     MATH 128   PHYS 110          0          0          2
36          36     MATH 128   PHYS 115          0          0          1

In [6]:
ranking = {}

sortedranking = 37
for i in range(sortedranking):
    mean = (df.iloc[i,3] + df.iloc[i,4] + df.iloc[i,5]) / 3
    ranking[df.iloc[i,1] + ' ' + df.iloc [i,2]] = mean

sortedranking = sorted(ranking.items(), key=lambda x:x[1], reverse=True)
print(sortedranking)

[('CHEM 120 MATH 110', 11.333333333333334), ('BIO 115 CHEM 120', 7.0), ('MATH 110 PHYS 110', 5.666666666666667), ('CHEM 120 MATH 114', 5.0), ('CHEM 120 MATH 120', 4.0), ('MATH 114 PHYS 110', 3.6666666666666665), ('BIO 130 CHEM 120', 3.0), ('MATH 120 PHYS 110', 2.6666666666666665), ('BIO 105 CHEM 120', 2.0), ('BIO 130 MATH 120', 2.0), ('BIO 105 MATH 110', 1.6666666666666667), ('CHEM 130 MATH 110', 1.6666666666666667), ('BIO 105 MATH 120', 1.3333333333333333), ('BIO 115 MATH 114', 1.3333333333333333), ('BIO 130 MATH 110', 1.3333333333333333), ('BIO 105 BIO 130', 1.0), ('BIO 115 MATH 110', 1.0), ('CHEM 120 MATH 128', 1.0), ('CHEM 120 PHYS 110', 1.0), ('CHEM 130 MATH 120', 1.0), ('CHEM 130 MATH 128', 1.0), ('CHEM 130 PHYS 230', 1.0), ('MATH 120 PHYS 115', 1.0), ('BIO 115 CHEM 130', 0.6666666666666666), ('BIO 115 MATH 120', 0.6666666666666666), ('BIO 115 MATH 128', 0.6666666666666666), ('CHEM 130 PHYS 110', 0.6666666666666666), ('MATH 128 PHYS 110', 0.6666666666666666), ('BIO 105 PHYS 110', 0.3333333333333333), ('BIO 105 CHEM 130', 0.3333333333333333), ('BIO 105 MATH 114', 0.3333333333333333), ('BIO 115 PHYS 110', 0.3333333333333333), ('BIO 115 PHYS 230', 0.3333333333333333), ('BIO 130 CHEM 130', 0.3333333333333333), ('BIO 130 MATH 128', 0.3333333333333333), ('CHEM 130 MATH 114', 0.3333333333333333), ('MATH 128 PHYS 115', 0.3333333333333333)]

In [7]:
# OLD???
from re import M
a_list = ['BIO 105','CHEM 120','PHYS 110','MATH 128']

def combine_pairs(my_list: list[str]):
    combinations = list(itertools.combinations(a_list, 2))
    return combinations

def alter_pairs(my_list: list[str]):
    combinations = combine_pairs(my_list)
    new_list = []
    for i in range(len(my_list)):
        new_list.append(combinations[i][0] + " " + combinations[i][1])
    return new_list

def check_pairs(my_list: list[str]):
    a = 0
    for i in range(len(sortedranking)):
        for j in range(len(my_list)):
            if sortedranking[i][0] == my_list[j]:
                a += sortedranking[i][1]
    return a

def list_to_score(my_list: list[str]):
    return check_pairs(alter_pairs(combine_pairs(my_list)))

list_to_score(a_list)

4.333333333333333

In [42]:
# MOST RECENT
a_list = ['BIO 105','CHEM 120','PHYS 110','MATH 110']


def combine_pairs(my_list: list[str]):
    a = list(itertools.combinations(my_list, 2))
    y = [' '.join(i) for i in a]
    return y

def alphabetize_pairs(pair: str):
    a = pair.find(" ") + 1
    space = pair.find(" ", a)
    if pair[0] > pair[space + 1]:
        pair = pair[space + 1:] + ' ' + pair[0:space]
        return pair

def alphabetize_list(my_list: list[str]):
    final = []
    for i in range(len(my_list)):
        a = my_list[i].find(" ") + 1
        space = my_list[i].find(" ", a)
        if my_list[i][0] > my_list[i][space + 1]:
            final.append(alphabetize_pairs(my_list[i]))
        else:
            final.append(my_list[i])
    return final


def check_pairs(my_list: list[str]):
    total_coenrolls = 0
    for i in range(len(sortedranking)):
        for j in range(len(my_list)):
            if sortedranking[i][0] == my_list[j]:
                total_coenrolls += sortedranking[i][1]
                print(sortedranking[i][0], "have a co-enrollment score of", sortedranking[i][1])
    return total_coenrolls

def list_to_score(my_list: list[str]):
    return check_pairs(alphabetize_list(combine_pairs(a_list)))

print("Total mean value of schedule:", (a_list), ":", list_to_score(a_list))
print("A higher co-enrollment score means that this set of classes is more commonly taken together.")

CHEM 120 MATH 110 have a co-enrollment score of 11.333333333333334
MATH 110 PHYS 110 have a co-enrollment score of 5.666666666666667
BIO 105 CHEM 120 have a co-enrollment score of 2.0
BIO 105 MATH 110 have a co-enrollment score of 1.6666666666666667
CHEM 120 PHYS 110 have a co-enrollment score of 1.0
BIO 105 PHYS 110 have a co-enrollment score of 0.3333333333333333
Total mean value of schedule: ['BIO 105', 'CHEM 120', 'PHYS 110', 'MATH 110'] : 22.0
A higher co-enrollment score means that this set of classes is more commonly taken together.